name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.7

    - name: Build Go server
      run: |
        cd cmd/app
        go build -o server .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build . -t ghcr.io/${{ github.repository }}/go-k8s-server:latest --label "runnumber=${GITHUB_RUN_ID}"
        docker push ghcr.io/${{ github.repository }}/go-k8s-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.6.0'

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.4.1
      with:
        minikube version: 'v1.31.0'
        kubernetes version: 'v1.25.9'
        driver: docker

    - name: Deploy to Minikube
      run: |
        helm upgrade --install go-server ./deploy/helm/go-server-chart --namespace default
